services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=doc
      - POSTGRES_PASSWORD=doc
      - POSTGRES_DB=apivenda
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
      - apivenda_data:/var/lib/postgresql

volumes:
  apivenda_data:

