spring.application.name=api-crud-venda-produto

spring.datasource.url=jdbc:postgresql://localhost:5432/apivenda
spring.datasource.username=docker
spring.datasource.password=docker

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true