spring.application.name=api-crud-venda-produto

spring.datasource.url=jdbc:postgresql://localhost:5432/apivenda
spring.datasource.username=doc
spring.datasource.password=doc

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true